### ISSUE TITLE
Update to latest stylelint version

### ISSUE THREAD

**Issue by jens-duttke** [ssivanatarajan/stylelint-selector-no-empty#5]
Instead of using `stylelint` as dependency, wouldn't it make sense to define it as `peerDependencies`?
And beside that, the current stylelint version is 13.7.2, while this plugin is still relying on version 9.2.1, which has a vulnerability:
```
  Low             Prototype Pollution                                           

  Package         yargs-parser                                                  

  Patched in      >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2              

  Dependency of   stylelint-selector-no-empty [dev]                             

  Path            stylelint-selector-no-empty > stylelint > meow >              
                  yargs-parser                                                  

  More info       https://npmjs.com/advisories/1500
```
It's a really useful plugin, and it would be great to get that fixed.

**Comment by mjlehrke** [comment]
I agree. Stylelint docs/convention is to not have it as a dependency.

I did a brief test with the most recent stylelint version. This plugin seems to work just fine with that version and with setting it as a peer dependency.

**Comment by ssivanatarajan** [comment]
updated to latest stylelint version
