### ISSUE TITLE
Update stylelint version and define as peerDependency

### ISSUE THREAD

**Issue by carlosjeurissen** [ssivanatarajan/stylelint-selector-no-empty#8]
As mentioned in https://github.com/ssivanatarajan/stylelint-selector-no-empty/issues/5, it would make more sense for stylelint to be defined as peerDependency.

The stylelint version is also outdated, causing the following warning:
`WARN  deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown`.

Let me know if a PR is helpful.

**Comment by ssivanatarajan** [comment]
Thanks for reporting this issue . it has been fixed.

**Comment by carlosjeurissen** [comment]
Wonderful! Thanks! Changing the peerDependency to a range is preferred. Something like ">= 14.9.0". With the version number being the oldest stylelint this plugin supports.
