### ISSUE TITLE
version 1.0.9 producing stylelint errors

### ISSUE THREAD

**Issue by emuecksch-sz** [ssivanatarajan/stylelint-selector-no-empty#9]
The current version 1.0.9 is causing stylelint to throw the following Error in our environment:

```
Error: Cannot resolve custom syntax module "postcss-jsx". Check that module "postcss-jsx" is available and spelled correctly.

Caused by: Error: Cannot find module 'postcss-syntax/load-syntax'
```

Version 1.0.8 works just fine.

Any idea on this?

**Comment by carlosjeurissen** [comment]
Both `postcss-syntax` and `postcss-jsx` are not dependencies of this package. Did you try installing them in your repository and see if it solves your issue?

**Comment by emuecksch-sz** [comment]
installing `postcss-syntax` fixed the issue. How comes that using version 1.0.8 of this package was causing no errors?
Was `postcss-syntax` removed as a dependency in 1.0.9?

**Comment by carlosjeurissen** [comment]
@emuecksch-sz Potentially by accident the older version of stylelint was using either dependencies. v1.0.9 updated the stylelint being used.

**Comment by emuecksch-sz** [comment]
@carlosjeurissen seems possible.
Thanks for the fast reply and solution.

**Comment by carlosjeurissen** [comment]
@emuecksch-sz You are very welcome! :)
